# Default initial positions for multi_arm's ros2_control fake system

initial_positions:
  left_fr3_finger_joint1: 0
  left_fr3_joint1: 0
  left_fr3_joint2: 0
  left_fr3_joint3: 0
  left_fr3_joint4: -1.57
  left_fr3_joint5: 0
  left_fr3_joint6: 1.57
  left_fr3_joint7: 0
  right_fr3_finger_joint1: 0
  right_fr3_joint1: 0
  right_fr3_joint2: 0
  right_fr3_joint3: 0
  right_fr3_joint4: -1.57
  right_fr3_joint5: 0
  right_fr3_joint6: 1.57
  right_fr3_joint7: 0
